name: slack - GitHub Actions Slack integration + custom
description: Notify Slack of GitHub Actions workflows, jobs and step status.
author: satterly
inputs:
  status:
    description: Specify success, failure, cancelled or a custom status.
    required: true
  steps:
    description: Report on the status of individual steps
    required: false
  channel:
    description: Override default channel with different channel or username
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: alert-circle
  color: red
